[package]
name = "optimize_rs"
version = "0.1.0"
edition = "2024"

[lib]
name = "_optimize_rs"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "*", features = ["extension-module"] }
optimize_engine = { path = "../engine" }
